sudo: false
language: python
python:
  - 3.6
services:
  - docker
before_install:
  - docker network create --subnet=172.17.0.0/16 testnetwork
  - docker pull moonlitlaputa/travis-ci-postgres
  - docker run --net testnetwork --ip 172.17.0.1 -d moonlitlaputa/travis-ci-postgres
  - docker ps -a
install:
  - pip install .
script: blog-manager test
after_success:
  - export FLASK_COVERAGE=True
  - blog-manager test
