"""empty message

Revision ID: dcf21d7a16f3
Revises: f3c50d5afbac
Create Date: 2019-03-02 21:20:20.224477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf21d7a16f3'
down_revision = 'f3c50d5afbac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.drop_constraint('book_creater_id_fkey', 'book', type_='foreignkey')
    op.create_foreign_key(None, 'book', 'users', ['creator_id'], ['id'])
    op.drop_column('book', 'creater_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('creater_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.create_foreign_key('book_creater_id_fkey', 'book', 'users', ['creater_id'], ['id'])
    op.drop_column('book', 'creator_id')
    # ### end Alembic commands ###
