"""add kindle email

Revision ID: f3c50d5afbac
Revises: 7de42cf6ce0e
Create Date: 2019-03-02 15:46:15.895806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c50d5afbac'
down_revision = '7de42cf6ce0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('kindle_email', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'kindle_email')
    # ### end Alembic commands ###
